# For details of the below fields, please refer CUSTOMISE.md
PROJECT_NAME: cataract_bot_hierarchy
CHAT_APPLICATION: whatsapp
API_ACTIVATED: true
USERS : ['Patient']
EXPERTS:
  Doctor: 'medical'
  Counsellor: 'logistical'
USER_PROMPT : 'You are a cataract bot. Your purpose is to help patients with any queries that they might have.'

RECREATE_EMBEDDINGS: false
SHOW_CITATIONS: true
SEND_POLL: true
SEND_CONSENSUS_POLL: true
SUGGEST_NEXT_QUESTIONS: true
MAX_CONVERSATION_LENGTH: 5
GLOB_SUFFIX: '*.txt'
PREVERIFIED: false

WELCOME_MESSAGES:
  USERS:
    - 'Hi! I am a cataract bot. I can help you with any queries that you have regarding your cataract surgeries.'
  EXPERTS:
    - 'Hi! I am a cataract bot. Thank you for volunteering to help patients with their science queries.'
SUGGESTION_QUESTIONS:
  - 'How can I prepare myself for Cataract Surgery?'
  - 'How safe is Cataract Surgery?'
  - 'How long does it take to recover from surgery?'

LANGUAGES:
  - en
  - hi
  - te
  - ta
  - kn
  - ur
 
COSMOS_DB_NAME: cataract-bot-test
AZURE_BLOB_CONTAINER_NAME: swaasthya-bot-audio-storage


COSMOS_USER_COLLECTION: users
COSMOS_RELATIONS_COLLECTION: relations
COSMOS_USER_CONV_COLLECTION: user_conversations
COSMOS_BOT_CONV_COLLECTION: bot_conversations
COSMOS_EXPERT_CONV_COLLECTION: expert_conversations
COSMOS_LOGGING_COLLECTION: 'logs'